### PR TITLE
Master

### PR DESCRIPTION
**Pull request by cyrsis**
Hi there, you have such a nice collection, I would like to add some more for your reference

### CODE REVIEW

**Comment by xinghongfei** [comment]
@cyrsis if you like this projection (https://github.com/xinghongfei/Hello-RxJava），i hope you could do something ,thx.

**Comment by cyrsis** [comment]
Sure, i get to it right the way

**Comment by xinghongfei** [comment]
that's great!!

**Comment by cyrsis** [comment]
Can you do more tutorial on Rx, I like to be the best Android programmer, if u have anything I can add more to it. You and I can make a good team

**Comment by xinghongfei** [comment]
that's great,i hope i can do something about android with you ,very interesting. but now is the best time ,i have many things to do ,because i will finish school next year,i need to find a job.

**Comment by cyrsis** [comment]
I already have a job in hk, it just dont pay well. Plan to do a startup and do something for myself. But I am a C# windows programmer, there is no room for a startup using windows anymore.

That is why I am here, learning Android for 2 weeks for now. And Android is EASY!!!!!!. 

Do you know any way to make android development FAST?  

I want to do something crazy ..like 1 days 1 complete android app to the Market

**Comment by xinghongfei** [comment]
in begin ,the faster way to learn android is to look video,www.imooc.com has some best tutorial. than  read google guide.

**Comment by cyrsis** [comment]
Thanks, I think I already known those materials. Android is pretty easy to learn. I will try to make my own app within next week to the market. And the teacher is not FAST enough

**Comment by xinghongfei** [comment]
good luck

**Pull request merged**
